menu:
  archives: /archives
  projects: https://github.com/rayliao
  rss: /atom.xml

logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png

favicon: /images/favicon.png

# Comment
# e.g disqus: greenbit
disqus:
duoshuo:
gitalk:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
